### PR TITLE
Feature/scheduling function fixes

### LINKED ISSUE #156: Create a scheduling function for getting issue data for a service
Create method(s) for fetching issue data from Github. Add a schedule to run the method periodically.

# Goal
Make sure our local collection of Github issues stays in sync with Github as issues are added, updated, and closed. This means at any given time, our collection will have the same information as Github. E.g.

- correct details for all issues
  - open date
  - update date
  - closed date
  - Issue title
  - Labels

We can ask Github for ALL issues every time this function runs, but that may prove to be inefficient. Instead, we want to ask Github for only issues that have changed since a given time, regardless of whether they are still open.

# Definition of done

* [x] Method exists for fetching all issue data from Github repository.
* [x] Method takes as a argument a specified timeframe.
* [x] When a service is added to portal, schedule starts to run periodically after initial pull.
* [ ] *All* issues having recent changes are synchronized when scheduling function runs
  - This means that we only receive issues that have changed
  - changed issues can mean they were closed since last run

### PR DESCRIPTION
**Pull request by Alapan**
Closes #156

# Proposed changes
(List any significant changes or additions here)
- State 'all' property used in call to API to fetch closed issues as well

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

File: integrations/github/issues/server/methods.js [hunk 1]
```diff
@@ -78,5 +78,50 @@ Meteor.methods({
         syncComplete = true;
       }
     }
+  },
+  getNewAndUpdatedIssuesSinceDate (user, repo, date) {
```
Comment (brylie) [inline integrations/github/issues/server/methods.js]: One more thing, our Github related methods start with the word github. So, at the risk of exceeding 80 characters, lets prefix this method name with github and shorten if possible.

File: integrations/github/issues/server/methods.js [hunk 2]
```diff
@@ -78,5 +78,50 @@ Meteor.methods({
...
+        since: date
+      }, (err, data) => {
+        done(null, data);
+      });
+    }); 
+
+    const issues = response['result'];
+  
+    if (issues.length > 0) {  
+      _.each(issues, (issue) => {
```
Comment (brylie) [inline integrations/github/issues/server/methods.js]: This `_.each()` loop may be unnecessary now, since the Github API call should only return issues created or updated after the last run.

**Comment by brylie** [comment]
I marked this as WIP, as there seems to be at least one logical error in the code.

File: integrations/github/server/cron.js [hunk 3]
```diff
@@ -14,7 +14,12 @@ Meteor.startup(function() {
         const allSources = Sources.find();
         allSources.forEach(function(source){
           // convert lastJobEndTime time to ISO-8601 format, required for comparisons later on
-          Meteor.call('getNewAndUpdatedIssuesSinceDate', source.github.user, source.github.repo, lastJobEndTime.toISOString());
+          const issues = Meteor.call('githubSyncRecentIssueChanges', source.github.user, source.github.repo, lastJobEndTime.toISOString());
+
+          // update GithubIssues collection is number of updated issues is non-zero
+          if (issues.length > 0) {
+            Meteor.call('githubSyncUpdatedIssues', source.github.repo);
```
Comment (brylie) [inline integrations/github/server/cron.js]: The call to `githubSyncUpdatedIssues` is missing the first parameter, which should be an array of issues from the previous step.

File: integrations/github/server/cron.js [hunk 4]
```diff
@@ -14,7 +14,12 @@ Meteor.startup(function() {
         const allSources = Sources.find();
         allSources.forEach(function(source){
           // convert lastJobEndTime time to ISO-8601 format, required for comparisons later on
-          Meteor.call('getNewAndUpdatedIssuesSinceDate', source.github.user, source.github.repo, lastJobEndTime.toISOString());
+          const issues = Meteor.call('githubSyncRecentIssueChanges', source.github.user, source.github.repo, lastJobEndTime.toISOString());
```
Comment (brylie) [inline integrations/github/server/cron.js]: When lines get this long, we can shorten them by using variables to hold the values. E.g.:

```
const username = source.github.user;
const repository = source.github.repo;
const lastRun = lastJobEndTime.toISOString();

const issues = Meteor.call('githubSyncRecentIssueChanges, username, repository, lastRun);
```

More vertical space is alright, as it is easy to read.

File: integrations/github/issues/server/methods.js [hunk 5]
```diff
@@ -78,5 +78,51 @@ Meteor.methods({
         syncComplete = true;
       }
     }
+  },
+  githubSyncRecentIssueChanges (user, repo, date) {
```
Comment (brylie) [inline integrations/github/issues/server/methods.js]: This function looks great. One small change, for semantics, would be to rename the function to `githubGetRecentIssueChanges`, since this function is really just a getter.

**Comment by brylie** [comment]
I have reviewed the code, and made a few minor changes. Please test this PR, and verify the following:

- [ ] `githubGetRecentIssueChanges` returns an array of recent issue changes, including closed issues
- [ ] `githubSyncUpdatedIssues` creates or replaces existing issues in the GithubIssues collection
- [ ] the Synced Cron `Get Github issue data for service` job performs both actions correctly, and on the interval specified
- [ ] the SyncedCron `Get Github issue data for service` contains only code related to Github Issues, e.g. there is no commit related code therein

**Comment by brylie** [comment]
Also, be aware of the following bug report:
https://github.com/Digipalvelutehdas/dipor-dashboard/issues/247

Basically, we need to test that the cron job succeeds on a second run, and possibly a third run.

File: integrations/github/server/cron.js [hunk 6]
```diff
@@ -23,12 +23,8 @@ Meteor.startup(function() {
 
           // update GithubIssues collection is number of updated issues is non-zero
           if (issues.length > 0) {
-            Meteor.call('githubSyncUpdatedIssues', repository, issues);
+            Meteor.call('githubSyncUpdatedIssues', issues);
           }
-          // other calls
-          Meteor.call('githubGetCommitActivity', username, repository);
```
Comment (brylie) [inline integrations/github/server/cron.js]: Move these method calls to a different cron task, rather than just deleting them.

**Comment by brylie** [comment]
This cron task will need to check for the last time it ran, but the code currently ]checks for the last time *any* cron job ran](https://github.com/Digipalvelutehdas/dipor-dashboard/blob/feature/scheduling-function-fixes/integrations/github/server/cron.js#L11).

File: integrations/github/issues/server/methods.js [hunk 7]
```diff
@@ -78,5 +78,48 @@ Meteor.methods({
...
+    /*
+    Update GithubIssues repo with all issues new/updated/closed
+    since  the time the job last ran
+    @param {string} issues - Issues array
+    @param {string} repo - repo name
+    */
+    _.each(issues, (issue) => {
+      const existingIssue = GithubIssues.findOne({
+        id: issue.id,
+        number: issue.number
```
Comment (brylie) [inline integrations/github/issues/server/methods.js]: This field is not needed to uniquely identify the issue. The `id: issue.id` should be sufficient, as all Github issues have a unique `id`.

File: integrations/github/issues/server/methods.js [hunk 8]
```diff
@@ -78,5 +78,48 @@ Meteor.methods({
...
     }
+  },
+  githubGetRecentIssueChanges (user, repo, date) {
+
+    /*
+    Get all new and updated issues for a particular repository
+    since the last job ran.
+    @param {string} user - The Github username or organization.
+    @param {string} repo - The Github repository name associated with the user.
+    @param {string} date - the time when the last job finished
```
Comment (brylie) [inline integrations/github/issues/server/methods.js]: This comment should be changed to be more generic:

```
 @param {string} date - get issues added or updated after this date
```

I.e. this method may be called in different contexts than our SyncedCron function, so the `time when the last job finished` may not be meaningful

**Comment by Alapan** [comment]
@brylie I made the changes
