### PR TITLE
Fix query string

### LINKED ISSUE #332: Inconsistency in no. of issue between dipor visualization and original github repository
> Use this section for a bug report

# Short bug title
There is mismatch in no. of open and closed issues between dipor dashboard visualization and original github repository

# Steps to reproduce

1. https://dashboard.digipalvelutehdas.fi
2. go to Organizations   Nazia's Test Organization   Digipalvelutehdas   Dipor Dashboard
3. Hover on donut chart for issues
4. monitor no. of open and closed issues.
5. go to original repository in github
6. click on issue tab

# Observed behavior
No. of issues (both open and closed) mismatches in both places

# Expected behavior
The number should be consistent in both place

# Environment

- chrome
- windows 8
**Note:** Some of the above details will be added during the discussion and testing process.

### PR DESCRIPTION
**Pull request by jykae**
Closes #332 

# Proposed changes
- Fix query string

@Digipalvelutehdas/dipor-team please review.

### CODE REVIEW

File: services/client/single/sources/issueCountsChart/issueCountsChart.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ Template.issueCountsChart.onCreated(function (){
   const repo = instance.data.repo;
 
   // Get open issues for organization
-  const openIssuesQuery = {q: "user:"+user+"+repo:"+repo+"+type:issue+state:open"};
+  const openIssuesQuery = {q: "repo:"+user+"/"+repo+"+type:issue+state:open"};
```
Comment (brylie) [inline services/client/single/sources/issueCountsChart/issueCountsChart.js]: Can we construct the query string within the `searchIssues function` and submit the configuration parameters:
- user
- repo
-state

**Comment by brylie** [comment]
Is there a related bug or issue for this PR?

File: services/client/single/sources/issueCountsChart/issueCountsChart.js (hunk 1 above)
Comment (jykae) [inline services/client/single/sources/issueCountsChart/issueCountsChart.js]: good idea, should be done on the function side. This is error prone.

Comment (jykae) [inline services/client/single/sources/issueCountsChart/issueCountsChart.js]: @brylie we had talk on daily that this could be done using our cron synced data, and not with additional REST calls, as this is called with Async.runSync

I will try to use our existing functions instead straight API call.

Comment (jykae) [inline services/client/single/sources/issueCountsChart/issueCountsChart.js]: @brylie we have also PRs in our GithubIssues collection, how can I tell difference between normal issue and PR? I found that only Search API provides easy way for that.

Comment (jykae) [inline services/client/single/sources/issueCountsChart/issueCountsChart.js]: This gives 210 (apinf/api-umbrella-dashboard) currently.
```
GithubIssues.find({"user": user, "repository": repository, state: "open"}).count()
210
```

**Comment by jykae** [comment]
@brylie Improved the function. We should probably use the Search API in cron sync functions to get issue type that we can tell difference between "issue" and "PR"

**Comment by brylie** [comment]
Good suggestion. I opened an issue to track the sync function improvement #349
